server:
    port: 1000
    servlet:
        context-path: /
    undertow:
        io-threads: 4
        worker-threads: 40
        direct-buffers: true
# 数据源配置
spring:
    main:
        allow-bean-definition-overriding: true
#    messages:
#        # 国际化资源文件路径
#        basename: static/i18n/messages
    # 文件上传
    servlet:
        multipart:
            # 单个文件大小
            max-file-size:  10MB
            # 设置总上传的文件大小
            max-request-size:  20MB
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.0.0.84:3306/gmall_pms?characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: WXwx@123
        #初始化连接
        initialSize: 5
        #最大连接数量
        maxActive: 50
        #最大空闲连接
        maxIdle: 10
        #最小空闲连接
        minIdle: 5
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://10.0.0.84:3306/gmall_pms?characterEncoding=UTF-8&serverTimezone=GMT%2B8
                username: root
                password: WXwx@123
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: jdbc:mysql://10.0.0.84:13306/gmall_pms?characterEncoding=UTF-8&serverTimezone=GMT%2B8
                username: root
                password: root
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username:
                login-password:
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

    redis:
        # 单机配置
        host: 10.0.0.84
        port: 6379
        database: 1
        password:
        # 集群配置
        #    cluster:
        #      nodes: 10.0.0.84:16379
        # 连接超时时间
        timeout: 1000
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
#spring:
    cloud:
        nacos:
            discovery:
                server-addr: 10.0.0.84:8848
    application:
        name: guli-product
#  logging:
#    config: classpath:logback.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mybatis-plus:
    configuration:
        call-setters-on-nulls: true
        default-statement-timeout: 60
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:/mapper/**/*.xml
    global-config:
        #数据库相关配置
        db-config:
            #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
            id-type: AUTO
            logic-delete-value: -1
            logic-not-delete-value: 0
        banner: false